# Generated by Django 2.2.9 on 2019-12-21 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='display_days',
        ),
        migrations.RemoveField(
            model_name='store',
            name='end_hour',
        ),
        migrations.RemoveField(
            model_name='store',
            name='start_hour',
        ),
    ]
