# Generated by Django 2.2.9 on 2019-12-23 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_auto_20191224_0222'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='schedule',
            name='unique_data',
        ),
    ]
